apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  labels:
    app: student-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-management
        image: pranit007/student-management-system
        ports:
        - containerPort: 8000
